language: go

go:
  - 1.14
  - 1.13

# Skip install step
install: true

# Generate and test
script:
  - GO15VENDOREXPERIMENT=1 go generate ./lc-lib/config ./lc-lib/core
  - GO15VENDOREXPERIMENT=1 go test -v . ./lc-tlscert ./lc-admin ./lc-lib/...
