#!/bin/bash

adduser --quiet --system --home /var/lib/log-courier --no-create-home --group log-courier
chown log-courier: /var/lib/log-courier /var/run/log-courier

if [ -f /var/run/log-courier.pid ]; then
	mv /var/run/log-courier.pid /var/run/log-courier/log-courier.pid
fi
