general:
  log syslog: false
  log stdout: true
receivers:
- listen:
  - 0.0.0.0:12345
pipelines:
- if: event.type == "nginx"
  then:
  - name: grok
    field: message
    remove: true
    patterns:
    - '^(?P<clientip>%{IPV4}|%{IPV6}) (?P<identd>[^ ]+) (?P<auth>[^ ]+) \[%{HTTPDATE:timestamp}\] \"(?:(?P<verb>[^ ]+) (?P<request>([^ \"\\]+|\\.)+)(?: HTTP/%{NUMBER:httpversion:float})?|(?P<rawrequest>([^\"]|\\.)*))\" %{NUMBER:response:int} (?:%{NUMBER:bytes:int}|-) \"(?P<referrer>(?:[A-Za-z][A-Za-z+\-.]*://(?P<referrer_host>(?:[^\"\\/]+|\\[^/])*)(?:[^\"\\]+|\\.)*|(?:[^\"\\]+|\\.)*))\" \"(?P<useragent>(?:[^\"\\]+|\\.)*)\" \"(?P<forwardedfor>(?:[^\"\\]+|\\.)*)\"'
  - name: add_tag
    tag: access_logs
  - name: date
    field: timestamp
    remove: true
    formats:
    - '02/Jan/2006:15:04:05 -0700'
  - name: geoip
    field: clientip
  - name: user_agent
    field: useragent
    remove: true
- else:
  - name: add_tag
    tag: unknown_event
network:
  transport: es
  index pattern: access-%{+2006.01.02}
  servers:
  - 127.0.0.1:9200
