source 'https://rubygems.org'

gemspec

group :development do
  gem 'rake'
  gem 'rubocop'
  gem 'logstash-devutils'
  gem 'logstash-core', :path => '../logstash/logstash-core'
  gem 'logstash-core-plugin-api', :path => "../logstash/logstash-core-plugin-api"
  gem 'log-courier', :path => '../log-courier'
end

group :test do
  gem 'rspec', '~> 3.1'
  gem 'rspec-core', '~> 3.1'
end
