source 'https://rubygems.org'

gemspec

# Profiler for MRI
gem 'ruby-prof', '~> 1.4.3', :platforms => :mri, :group => 'test'

# Log Courier gem JSON parsers
# TODO(Driskell): Move these into platform specific gems?
gem 'oj', '~> 3.13.9', :platforms => :mri
gem 'jrjackson', '~> 0.4.11',  :platforms => :jruby

group :development do
  gem 'rake'
  gem 'rubocop'
end

group :test do
  gem 'rspec', '~> 3.10.0'
  gem 'rspec-core', '~> 3.10.1'
end
