name: Ruby Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'ruby/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'ruby/**'

jobs:
  test_log_courier:
    strategy:
      matrix:
        # Logstash 7.7.0 is our earliest supported version, which uses JRuby 9.2.11.1, compatible with Ruby 2.5.x
        # Test also against 9.3.1.0 which is latest version and comaptible with Ruby 2.6.x
        ruby: ['ruby-2.5.9', 'jruby-9.2.11.1', 'ruby-2.6.8', 'jruby-9.3.1.0']
    name: Test Log Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        cd ruby/log-courier
        bundle install
        bundle exec rake

  test_logstash_input_courier:
    strategy:
      matrix:
        # Logstash 7.7.0 is our earliest supported version, which uses JRuby 9.2.11.1, compatible with Ruby 2.5.x
        # Test also against 9.3.1.0 which is latest version and comaptible with Ruby 2.6.x
        # (Only against JRuby though, as Logstash requires JRuby)
        ruby: ['jruby-9.2.11.1', 'jruby-9.3.1.0']
    name: Test Logstash Input Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        cd ruby/logstash-input-courier
        ./download_logstash.sh
        bundle install
        bundle exec rake

  test_logstash_output_courier:
    strategy:
      matrix:
        # Logstash 7.7.0 is our earliest supported version, which uses JRuby 9.2.11.1, compatible with Ruby 2.5.x
        # Test also against 9.3.1.0 which is latest version and comaptible with Ruby 2.6.x
        # (Only against JRuby though, as Logstash requires JRuby)
        ruby: ['jruby-9.2.11.1', 'jruby-9.3.1.0']
    name: Test Logstash Output Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        cd ruby/logstash-output-courier
        ./download_logstash.sh
        bundle install
        bundle exec rake
