name: Ruby

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'ruby/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'ruby/**'

jobs:
  test_log_courier:
    strategy:
      matrix:
        # Test against 9.4.12.0 (latest as of 01-03-2025)
        # Also test on Ruby 3.2, 3.3 and 3.4 (latest as of 01-03-2025)
        ruby: ['jruby-9.4.12.0', 'ruby-3.2.7', 'ruby-3.3.7', 'ruby-3.4.2']
    name: Test Log Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
        cd ruby/log-courier
        bundle install
        bundle exec rake

  test_logstash_input_courier:
    strategy:
      matrix:
        # Test against 9.4.12.0 (latest as of 01-03-2025)
        ruby: ['jruby-9.4.12.0']
    name: Test Logstash Input Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load cached Logstash
      id: cache-logstash
      uses: actions/cache@v3
      with:
        path: ruby/logstash
        key: logstash-${{ runner.os }}-${{ hashFiles('ruby/setup_logstash.sh') }}
    - name: Bootstrap Logstash for development
      if: steps.cache-logstash.outputs.cache-hit != 'true'
      run: |
        cd ruby
        ./setup_logstash.sh
    - name: Test
      run: |
        cd ruby/logstash-input-courier
        bundle install
        bundle exec rake

  test_logstash_output_courier:
    strategy:
      matrix:
        # Test against 9.4.12.0 (latest as of 01-03-2025)
        ruby: ['jruby-9.4.12.0']
    name: Test Logstash Output Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load cached Logstash
      id: cache-logstash
      uses: actions/cache@v3
      with:
        path: ruby/logstash
        key: logstash-${{ runner.os }}-${{ hashFiles('ruby/setup_logstash.sh') }}
    - name: Bootstrap Logstash for development
      if: steps.cache-logstash.outputs.cache-hit != 'true'
      run: |
        cd ruby
        ./setup_logstash.sh
    - name: Test
      run: |
        cd ruby/logstash-output-courier
        bundle install
        bundle exec rake
