name: Ruby

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'ruby/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'ruby/**'

jobs:
  test_log_courier:
    strategy:
      matrix:
        # Logstash 8.0.0 is our earliest supported version, which uses JRuby 9.2.20.1, compatible with Ruby 2.5.x
        # Test also against 9.3.10.0 which is latest version and comaptible with Ruby 2.6.x
        # NOTE: Logstash seems to fail on 9.4.1.0 which is latest version and comaptible with Ruby 3.1.x (latest 3.1.3 at time of writing)
        ruby: ['ruby-2.5.9', 'jruby-9.2.20.1', 'ruby-2.6.10', 'jruby-9.3.10.0']
    name: Test Log Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: |
        cd ruby/log-courier
        bundle install
        bundle exec rake

  test_logstash_input_courier:
    strategy:
      matrix:
        # Logstash 8.0.0 is our earliest supported version, which uses JRuby 9.2.20.1, compatible with Ruby 2.5.x
        # Test also against 9.3.10.0 which is latest version and comaptible with Ruby 2.6.x
        # NOTE: Logstash seems to fail on 9.4.1.0 which is latest version and comaptible with Ruby 3.1.x (latest 3.1.3 at time of writing)
        ruby: ['jruby-9.2.20.1', 'jruby-9.3.10.0']
    name: Test Logstash Input Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load cached Logstash
      id: cache-logstash
      uses: actions/cache@v3
      with:
        path: ruby/logstash
        key: logstash-${{ runner.os }}-${{ hashFiles('ruby/setup_logstash.sh') }}
    - name: Bootstrap Logstash for development
      if: steps.cache-logstash.outputs.cache-hit != 'true'
      run: |
        cd ruby
        ./setup_logstash.sh
    - name: Test
      run: |
        cd ruby/logstash-input-courier
        bundle install
        bundle exec rake

  test_logstash_output_courier:
    strategy:
      matrix:
        # Logstash 8.0.0 is our earliest supported version, which uses JRuby 9.2.20.1, compatible with Ruby 2.5.x
        # Test also against 9.3.10.0 which is latest version and comaptible with Ruby 2.6.x
        # NOTE: Logstash seems to fail on 9.4.1.0 which is latest version and comaptible with Ruby 3.1.x (latest 3.1.3 at time of writing)
        ruby: ['jruby-9.2.20.1', 'jruby-9.3.10.0']
    name: Test Logstash Output Courier ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Load cached Logstash
      id: cache-logstash
      uses: actions/cache@v3
      with:
        path: ruby/logstash
        key: logstash-${{ runner.os }}-${{ hashFiles('ruby/setup_logstash.sh') }}
    - name: Bootstrap Logstash for development
      if: steps.cache-logstash.outputs.cache-hit != 'true'
      run: |
        cd ruby
        ./setup_logstash.sh
    - name: Test
      run: |
        cd ruby/logstash-output-courier
        bundle install
        bundle exec rake
