name: Rubygems (Testing)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'ruby/**'

jobs:
  package_log_courier:
    name: Build Log Courier
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'jruby-9.3.15.0'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Package
      run: |
        cd ruby/log-courier
        # Don't need the full bundle to package
        gem install rake
        rake package
    - name: Upload Gem
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: log-courier
        path: ruby/log-courier/pkg/*.gem

  package_logstash_input_courier:
    name: Build Logstash Input Courier
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'jruby-9.3.15.0'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Package
      run: |
        cd ruby/logstash-input-courier
        # Don't need the full bundle to package
        gem install rake
        rake package
    - name: Upload Gem
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: logstash-input-courier
        path: ruby/logstash-input-courier/pkg/*.gem

  package_logstash_output_courier:
    name: Build Logstash Output Courier
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'jruby-9.3.15.0'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Package
      run: |
        cd ruby/logstash-output-courier
        # Don't need the full bundle to package
        gem install rake
        rake package
    - name: Upload Gem
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: logstash-output-courier
        path: ruby/logstash-output-courier/pkg/*.gem
